### ISSUE TITLE
Support to reading config for kubectl namespace

### ISSUE THREAD

**Issue by ymizushi** [ymizushi/dtt#8]
# Details

example toml file

```toml
[default]
shell = "/bin/sh"
[default.kubectl]
namespace = "sample-namespace"
```
